### ISSUE TITLE
Twitter feed

### ISSUE THREAD

**Issue by kyyberi** [apinf/apiops-meetup#31]
_From @kyyberi on October 15, 2015 5:30_

WE need to have apiops twitter feed on the page, possibly a bit like rebelmouse https://www.rebelmouse.com/ApiOps/

_Copied from original issue: APIOps/portal#6_

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup#23

**Comment by 55** [comment]
Implemented.
