### ISSUE TITLE
List events

### ISSUE THREAD

**Issue by kyyberi** [apinf/apiops-meetup#36]
_From @kyyberi on October 15, 2015 4:30_

As a APIOps community member I want to see list of APIOps events. From the list I want to open an event and see details such as location, time, date, participating members, description, organizer, map. 

_Copied from original issue: APIOps/portal#1_

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup#28

**Comment by 55** [comment]
Implemented.

**Comment by kyyberi** [comment]
Nice work!
