### ISSUE TITLE
Clear urls for meetups

### ISSUE THREAD

**Issue by kyyberi** [apinf/apiops-meetup#4]
http://apiops.net/meetups/mdYbfkJeDoSSS6jnM ->
http://apiops.net/meetups/28-11-2015-API-Jam-Tampere-Mikkeli

**Comment by 55** [comment]
Now URL looks like this: 
http://apiops.net/meetups/[meetupId]-[meetup-title]
http://apiops.net/meetups/226417050-api-jam-tampere-mikkeli

Can't make it as date for now.

**Comment by 55** [comment]
Created an issue about it https://github.com/todda00/meteor-friendly-slugs/issues/20

**Comment by kyyberi** [comment]
As it was discussed, date is not mandatory. The above looks good.
