### ISSUE TITLE
Move issues from old portal repo

### ISSUE THREAD

**Issue by 55** [apinf/apiops-meetup#6]
New Meetup website was transferred to APIOps organisation.
Issues from old portal repo are missing now.

@kyyberi could you please transfer them as you have time.

**Comment by kyyberi** [comment]
Those were moved to forked repo.

**Comment by kyyberi** [comment]
Old issues can be found from https://github.com/APIOps/portal/issues?q=is%3Aissue+is%3Aclosed I'll move those tonight

**Comment by 55** [comment]
@kyyberi, thanks. Sorry for deleting fork with already moved issues, that was the only way to transfer project to APIOps organization.

**Comment by kyyberi** [comment]
np

**Comment by kyyberi** [comment]
Did not have time yesterday. Flu getting worse. I'll do this as soon as it is possible but in a few days anyway.

**Comment by 55** [comment]
@kyyberi, okay, that's not blocking. Get well!

**Comment by kyyberi** [comment]
Done
